package compaction

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"
	"time"
)

// --- writeCompletionManifest ---

func TestWriteCompletionManifest_HappyPath(t *testing.T) {
	dir := t.TempDir()
	m := newTestManifest("db_cpu_123", CompletionStateOutputWritten)

	if err := writeCompletionManifest(dir, m); err != nil {
		t.Fatalf("writeCompletionManifest: %v", err)
	}

	final := filepath.Join(dir, m.JobID+".json")
	if _, err := os.Stat(final); err != nil {
		t.Fatalf("final file missing: %v", err)
	}
	// No tmp file left behind after a clean write.
	if _, err := os.Stat(final + ".tmp"); !os.IsNotExist(err) {
		t.Fatalf("tmp file should not exist after clean write: %v", err)
	}

	// File permissions should be 0600.
	info, err := os.Stat(final)
	if err != nil {
		t.Fatalf("stat: %v", err)
	}
	if perm := info.Mode().Perm(); perm != 0o600 {
		t.Errorf("file perm: got %o, want 0600", perm)
	}
}

func TestWriteCompletionManifest_CreatesMissingDir(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "nested", "deeper", ".completion", "pending")
	m := newTestManifest("db_cpu_456", CompletionStateOutputWritten)

	if err := writeCompletionManifest(dir, m); err != nil {
		t.Fatalf("writeCompletionManifest: %v", err)
	}

	// Dir should exist with 0700 perms.
	info, err := os.Stat(dir)
	if err != nil {
		t.Fatalf("stat dir: %v", err)
	}
	if perm := info.Mode().Perm(); perm != 0o700 {
		t.Errorf("dir perm: got %o, want 0700", perm)
	}
}

func TestWriteCompletionManifest_OverwritesExisting(t *testing.T) {
	dir := t.TempDir()
	m := newTestManifest("db_cpu_789", CompletionStateOutputWritten)

	// First write: state=output_written
	if err := writeCompletionManifest(dir, m); err != nil {
		t.Fatalf("first write: %v", err)
	}

	// Transition to sources_deleted and rewrite.
	m.State = CompletionStateSourcesDeleted
	m.DeletedSources = []string{"a.parquet", "b.parquet"}
	m.UpdatedAt = m.UpdatedAt.Add(time.Second)
	if err := writeCompletionManifest(dir, m); err != nil {
		t.Fatalf("second write: %v", err)
	}

	got, err := readCompletionManifest(filepath.Join(dir, m.JobID+".json"))
	if err != nil {
		t.Fatalf("readCompletionManifest: %v", err)
	}
	if got.State != CompletionStateSourcesDeleted {
		t.Errorf("state: got %q, want %q", got.State, CompletionStateSourcesDeleted)
	}
	if len(got.DeletedSources) != 2 {
		t.Errorf("DeletedSources: got %d, want 2", len(got.DeletedSources))
	}
}

func TestWriteCompletionManifest_RejectsNilManifest(t *testing.T) {
	if err := writeCompletionManifest(t.TempDir(), nil); err == nil {
		t.Fatal("expected error for nil manifest, got nil")
	}
}

func TestWriteCompletionManifest_RejectsEmptyJobID(t *testing.T) {
	m := newTestManifest("", CompletionStateOutputWritten)
	if err := writeCompletionManifest(t.TempDir(), m); err == nil {
		t.Fatal("expected error for empty JobID, got nil")
	}
}

// TestWriteCompletionManifest_RejectsPathTraversalInJobID exhaustively
// exercises every branch of validateJobID. Regression test for the
// Phase 4 security-review finding: the original check only rejected
// forward/back slashes, missing null bytes, "..", and leading dots.
// All four branches must reject so a malicious or buggy upstream JobID
// cannot escape the pending directory via filepath.Join.
func TestWriteCompletionManifest_RejectsPathTraversalInJobID(t *testing.T) {
	cases := []struct {
		name       string
		jobID      string
		wantSubstr string
	}{
		{"forward_slash", "foo/bar", "path separators"},
		{"backslash", "foo\\bar", "path separators"},
		{"absolute_forward", "/absolute", "path separators"},
		{"null_byte", "foo\x00bar", "null bytes"},
		{"relative_dotdot", "foo..bar", "'..'"},
		{"dotdot_only", "..", "'..'"},
		{"dotdot_trailing", "safe..", "'..'"},
		{"leading_dot", ".hidden", "'.'"},
		{"leading_dot_only", ".", "'.'"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			m := newTestManifest(tc.jobID, CompletionStateOutputWritten)
			err := writeCompletionManifest(t.TempDir(), m)
			if err == nil {
				t.Fatalf("expected error for JobID %q, got nil", tc.jobID)
			}
			if !strings.Contains(err.Error(), tc.wantSubstr) {
				t.Errorf("error for %q should mention %q, got: %v", tc.jobID, tc.wantSubstr, err)
			}
		})
	}
}

// TestWriteCompletionManifest_AcceptsValidJobIDs confirms the validator
// doesn't over-reject. The real JobIDs generated by NewJob have the
// shape "{database}_{partition_with_slashes_replaced}_{nanos}", which
// contains underscores and digits. Unicode letters and dashes are also
// accepted — we don't narrow to a strict allowlist.
func TestWriteCompletionManifest_AcceptsValidJobIDs(t *testing.T) {
	cases := []string{
		"simple",
		"mydb_cpu_2026_04_11_14_1234567890",
		"db-with-dashes_measurement",
		"UPPERCASE_OK",
		"unicode_café",
		"db_with.single_dot",
		"trailing_dot.",
	}
	for _, jobID := range cases {
		t.Run(jobID, func(t *testing.T) {
			m := newTestManifest(jobID, CompletionStateOutputWritten)
			if err := writeCompletionManifest(t.TempDir(), m); err != nil {
				t.Errorf("valid JobID %q unexpectedly rejected: %v", jobID, err)
			}
		})
	}
}

// --- readCompletionManifest ---

func TestReadCompletionManifest_RoundTrip(t *testing.T) {
	dir := t.TempDir()
	in := newTestManifest("rt_job_001", CompletionStateOutputWritten)
	in.Outputs = []CompactedOutput{
		{
			Path:          "db/cpu/2026/04/11/14/compacted_x.parquet",
			SHA256:        "deadbeef",
			SizeBytes:     12345,
			Database:      "db",
			Measurement:   "cpu",
			PartitionTime: time.Date(2026, 4, 11, 14, 0, 0, 0, time.UTC),
			Tier:          "hot",
			CreatedAt:     time.Date(2026, 4, 11, 14, 30, 0, 0, time.UTC),
		},
	}

	if err := writeCompletionManifest(dir, in); err != nil {
		t.Fatalf("write: %v", err)
	}

	got, err := readCompletionManifest(filepath.Join(dir, in.JobID+".json"))
	if err != nil {
		t.Fatalf("read: %v", err)
	}

	if got.JobID != in.JobID {
		t.Errorf("JobID: got %q, want %q", got.JobID, in.JobID)
	}
	if got.State != in.State {
		t.Errorf("State: got %q, want %q", got.State, in.State)
	}
	if len(got.Outputs) != 1 {
		t.Fatalf("Outputs: got %d, want 1", len(got.Outputs))
	}
	if got.Outputs[0].SHA256 != "deadbeef" {
		t.Errorf("Outputs[0].SHA256: got %q, want deadbeef", got.Outputs[0].SHA256)
	}
	if got.Outputs[0].SizeBytes != 12345 {
		t.Errorf("Outputs[0].SizeBytes: got %d, want 12345", got.Outputs[0].SizeBytes)
	}
	if !got.Outputs[0].PartitionTime.Equal(in.Outputs[0].PartitionTime) {
		t.Errorf("PartitionTime: got %v, want %v", got.Outputs[0].PartitionTime, in.Outputs[0].PartitionTime)
	}
}

func TestReadCompletionManifest_NotFound(t *testing.T) {
	if _, err := readCompletionManifest(filepath.Join(t.TempDir(), "missing.json")); err == nil {
		t.Fatal("expected error for missing file, got nil")
	}
}

func TestReadCompletionManifest_InvalidJSON(t *testing.T) {
	path := filepath.Join(t.TempDir(), "bad.json")
	if err := os.WriteFile(path, []byte("not json"), 0o600); err != nil {
		t.Fatalf("seed: %v", err)
	}
	if _, err := readCompletionManifest(path); err == nil {
		t.Fatal("expected unmarshal error, got nil")
	}
}

// --- listPendingCompletionManifests ---

func TestListPendingCompletionManifests_Empty(t *testing.T) {
	paths, err := listPendingCompletionManifests(t.TempDir())
	if err != nil {
		t.Fatalf("list: %v", err)
	}
	if len(paths) != 0 {
		t.Errorf("paths: got %d, want 0", len(paths))
	}
}

func TestListPendingCompletionManifests_MissingDirIsNotError(t *testing.T) {
	// listPendingCompletionManifests must not error on a missing dir —
	// that's the expected state on a node that has never run compaction,
	// and spamming the watcher logs would be wrong.
	paths, err := listPendingCompletionManifests(filepath.Join(t.TempDir(), "does-not-exist"))
	if err != nil {
		t.Fatalf("list: %v", err)
	}
	if paths != nil {
		t.Errorf("paths: got %v, want nil", paths)
	}
}

func TestListPendingCompletionManifests_SkipsTmpAndNonJSON(t *testing.T) {
	dir := t.TempDir()
	// Write 3 manifests + 1 .tmp + 1 foreign file.
	writeRaw(t, filepath.Join(dir, "a.json"), `{"job_id":"a","state":"output_written"}`)
	writeRaw(t, filepath.Join(dir, "b.json"), `{"job_id":"b","state":"output_written"}`)
	writeRaw(t, filepath.Join(dir, "c.json"), `{"job_id":"c","state":"output_written"}`)
	writeRaw(t, filepath.Join(dir, "in_progress.json.tmp"), `partial`)
	writeRaw(t, filepath.Join(dir, "README.md"), `ignore me`)

	paths, err := listPendingCompletionManifests(dir)
	if err != nil {
		t.Fatalf("list: %v", err)
	}
	if len(paths) != 3 {
		t.Fatalf("paths: got %d, want 3: %v", len(paths), paths)
	}
	// Sorted order: a, b, c.
	for i, want := range []string{"a.json", "b.json", "c.json"} {
		if filepath.Base(paths[i]) != want {
			t.Errorf("paths[%d]: got %q, want %q", i, filepath.Base(paths[i]), want)
		}
	}
}

func TestListPendingCompletionManifests_SkipsSubdirs(t *testing.T) {
	dir := t.TempDir()
	writeRaw(t, filepath.Join(dir, "real.json"), `{"job_id":"real"}`)
	if err := os.Mkdir(filepath.Join(dir, "subdir"), 0o700); err != nil {
		t.Fatalf("mkdir: %v", err)
	}

	paths, err := listPendingCompletionManifests(dir)
	if err != nil {
		t.Fatalf("list: %v", err)
	}
	if len(paths) != 1 {
		t.Fatalf("paths: got %d, want 1", len(paths))
	}
}

// --- deleteCompletionManifest ---

func TestDeleteCompletionManifest_HappyPath(t *testing.T) {
	path := filepath.Join(t.TempDir(), "gone.json")
	writeRaw(t, path, `{"job_id":"gone"}`)

	if err := deleteCompletionManifest(path); err != nil {
		t.Fatalf("delete: %v", err)
	}
	if _, err := os.Stat(path); !os.IsNotExist(err) {
		t.Errorf("file should be gone, got err: %v", err)
	}
}

func TestDeleteCompletionManifest_IdempotentOnMissing(t *testing.T) {
	// Deleting a non-existent file is the watcher's safe recovery path.
	if err := deleteCompletionManifest(filepath.Join(t.TempDir(), "never.json")); err != nil {
		t.Errorf("delete of missing file should not error, got: %v", err)
	}
}

// --- concurrent write/read (watcher polling during subprocess writes) ---

func TestConcurrentWriteAndRead(t *testing.T) {
	// Simulates the real-world pattern: subprocess rewrites the manifest
	// repeatedly (state transitions) while the watcher polls listPending +
	// readCompletionManifest concurrently. The atomic rename ensures the
	// reader either sees the previous state or the new state, never a torn
	// value. We can't reliably observe a torn read (it would be a bug), so
	// this test asserts the reader never sees a json.Unmarshal error.
	dir := t.TempDir()
	jobID := "concurrent_job"

	var wg sync.WaitGroup
	stop := make(chan struct{})

	// Writer: repeatedly rewrite the manifest, bumping UpdatedAt.
	wg.Add(1)
	go func() {
		defer wg.Done()
		m := newTestManifest(jobID, CompletionStateWritingOutput)
		for i := 0; ; i++ {
			select {
			case <-stop:
				return
			default:
			}
			m.UpdatedAt = m.UpdatedAt.Add(time.Millisecond)
			if i%3 == 1 {
				m.State = CompletionStateOutputWritten
			} else if i%3 == 2 {
				m.State = CompletionStateSourcesDeleted
			} else {
				m.State = CompletionStateWritingOutput
			}
			if err := writeCompletionManifest(dir, m); err != nil {
				t.Errorf("write iteration %d: %v", i, err)
				return
			}
		}
	}()

	// Reader: poll and try to read the manifest. Any unmarshal failure is
	// a torn read and indicates a bug in the atomic-rename pattern.
	wg.Add(1)
	go func() {
		defer wg.Done()
		deadline := time.Now().Add(200 * time.Millisecond)
		readCount := 0
		for time.Now().Before(deadline) {
			paths, err := listPendingCompletionManifests(dir)
			if err != nil {
				t.Errorf("list: %v", err)
				return
			}
			for _, p := range paths {
				if _, err := readCompletionManifest(p); err != nil {
					// A torn-read would fail json.Unmarshal here. That's
					// the bug we're guarding against.
					t.Errorf("torn read of %s: %v", p, err)
					return
				}
				readCount++
			}
		}
		if readCount == 0 {
			t.Errorf("reader never observed a manifest; timing issue in test")
		}
	}()

	// Let both goroutines run briefly, then stop.
	time.Sleep(200 * time.Millisecond)
	close(stop)
	wg.Wait()
}

// --- helpers ---

func newTestManifest(jobID string, state CompletionState) *CompletionManifest {
	now := time.Date(2026, 4, 11, 18, 0, 0, 0, time.UTC)
	return &CompletionManifest{
		JobID:         jobID,
		Database:      "testdb",
		Measurement:   "cpu",
		PartitionPath: "testdb/cpu/2026/04/11/14",
		Tier:          "hot",
		State:         state,
		Outputs: []CompactedOutput{
			{
				Path:          "testdb/cpu/2026/04/11/14/compacted_abc.parquet",
				SHA256:        "abc123",
				SizeBytes:     1024,
				Database:      "testdb",
				Measurement:   "cpu",
				PartitionTime: time.Date(2026, 4, 11, 14, 0, 0, 0, time.UTC),
				Tier:          "hot",
				CreatedAt:     now,
			},
		},
		CreatedAt: now,
		UpdatedAt: now,
	}
}

func writeRaw(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatalf("write raw %s: %v", path, err)
	}
}

// Guard against the JSON format silently changing — the fields encoded here
// are consumed by the cluster-side bridge via readCompletionManifest, and a
// rename or type shift would silently break that consumer. This lock-in
// test compiles the expected schema into the package.
func TestCompletionManifestJSONSchema(t *testing.T) {
	m := newTestManifest("schema_test", CompletionStateOutputWritten)
	m.DeletedSources = []string{"a.parquet"}
	data, err := json.Marshal(m)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	got := string(data)
	// Every field name the bridge depends on must appear in the marshaled
	// output. If a future refactor renames one, this test fires before the
	// bridge silently misbehaves.
	required := []string{
		`"job_id"`, `"database"`, `"measurement"`, `"partition_path"`, `"tier"`,
		`"state"`, `"outputs"`, `"deleted_sources"`, `"created_at"`, `"updated_at"`,
		// Per-output fields the bridge maps into raft.FileEntry.
		`"path"`, `"sha256"`, `"size_bytes"`, `"partition_time"`,
	}
	for _, field := range required {
		if !strings.Contains(got, field) {
			t.Errorf("expected field %s in marshaled manifest, got: %s", field, got)
		}
	}
}

// Prevent Go from stripping the fmt import if we remove the debug prints
// above in a refactor — the test helpers reference this once to keep it
// needed.
var _ = fmt.Sprintf
