{{- if and (not .Values.license.existingSecret) .Values.license.key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "arc-enterprise.licenseSecretName" . }}
  labels:
    {{- include "arc-enterprise.labels" . | nindent 4 }}
type: Opaque
stringData:
  license-key: {{ .Values.license.key | quote }}
{{- end }}
