{{- if and (eq (include "arc-enterprise.minioBundled" .) "true") (not .Values.minio.credentials.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "arc-enterprise.minioSecretName" . }}
  labels:
    {{- include "arc-enterprise.labels" . | nindent 4 }}
type: Opaque
stringData:
  root-user: {{ .Values.minio.credentials.rootUser | quote }}
  root-password: {{ .Values.minio.credentials.rootPassword | quote }}
{{- end }}
