apiVersion: v1
kind: Service
metadata:
  name: {{ include "arc-enterprise.writerName" . }}
  labels:
    {{- include "arc-enterprise.roleLabels" (dict "ctx" . "role" "writer") | nindent 4 }}
  {{- with .Values.service.writer.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.writer.type }}
  ports:
    - name: http
      port: {{ .Values.service.writer.port }}
      targetPort: 8000
  selector:
    {{- include "arc-enterprise.roleSelectorLabels" (dict "ctx" . "role" "writer") | nindent 4 }}
